services:
  app:
    build:
      context: .
      args:
        HF_AUTH_TOKEN: ${HF_AUTH_TOKEN}
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - ./logs:/app/logs
      - huggingface_cache:/root/.cache/huggingface
    env_file:
      - .env

volumes:
  huggingface_cache:
