services:
  app:
    build:
      context: .
      args:
        HF_AUTH_TOKEN: ${HF_AUTH_TOKEN}
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - ./logs:/app/logs
    env_file:
      - .env
    networks:
      - app_network

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - app_network

volumes:
  huggingface_cache:
  ollama_models:

networks:
  app_network:
    driver: bridge
